export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLISTS:"SET_PLAYLISTS",
    SET_TOPITEMS:"SET_TOPITEMS",
    SET_ALBUMS:"SET_ALBUMS",
    SET_PODCASTS:"SET_PODCASTS",
    SET_CURRENTTRACK:"SET_CURRENTTRACK",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_PLAYLIST_ID:"SET_PLAYLIST_ID",
    SET_PLAYER_STATE:"SET_PLAYER_STATE",
    SET_ARTIST:"SET_ARTIST",
    SET_ARTIST_ID:"SET_ARTIST_ID",
    SET_ALBUM_ID:"SET_ALBUM_ID",
    SET_SEARCH_TERM:"SET_SEARCH_TERM"
};